# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  terraform: circleci/terraform@3.0.0

workflows:
  version: 2
  deploy_infrastructure:
    jobs:
      - terraform/fmt:
          path: ./terraform
          checkout: true
          context: terraform
      - terraform/validate:
          path: ./terraform
          checkout: true
          context: terraform
          requires:
            - terraform/fmt
      - terraform/plan:
          path: ./terraform
          checkout: true
          context: terraform
          persist-workspace: true
          requires:
            - terraform/validate
      - hold:
          type: approval
          requires:
            - terraform/plan
      - terraform/apply:
          path: ./terraform
          attach-workspace: true
          context: terraform
          filters:
            branches:
              only: main
          requires:
            - hold
