# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  terraform: circleci/terraform@3.0.0

jobs:
  packer-init:
    docker:
      - image: hashicorp/packer
    steps:
      - checkout
      - run:
          name: Initialize
          command: packer init ./packer
  packer-validate:
    docker:
      - image: hashicorp/packer
    steps:
      - checkout
      - run:
          name: Validate base
          command: packer validate ./packer
  packer-fmt:
    docker:
      - image: hashicorp/packer
    steps:
      - checkout
      - run:
          name: Format
          command: packer fmt ./packer
  packer-build:
    docker:
      - image: hashicorp/packer
    steps:
      - checkout
      - attach_workspace:
          at: ~/packer
      - run:
          name: Build AMI
          command: packer build ./packer
          no_output_timeout: 15m

workflows:
  version: 2
  deploy_ami:
    jobs:
      - packer-init
      - packer-validate:
          requires:
            - packer-init
      - packer-fmt:
          requires:
            - packer-validate
      - packer-build:
          context: terraform
          requires:
            - packer-fmt
  deploy_infrastructure:
    jobs:
      - terraform/fmt:
          path: ./terraform
          checkout: true
      - terraform/validate:
          path: ./terraform
          checkout: true
          context: terraform
          requires:
            - terraform/fmt
      - terraform/plan:
          path: ./terraform
          checkout: true
          context: terraform
          persist-workspace: true
          requires:
            - terraform/validate
      - hold:
          type: approval
          filters:
            branches:
              only: main
          requires:
            - terraform/plan
      - terraform/apply:
          path: ./terraform
          attach-workspace: true
          context: terraform
          filters:
            branches:
              only: main
          requires:
            - hold
