---
# Generate granfa-agnet.yaml file from template

- name: Generate grafana-agent.yaml file
  template:
    src: "grafana-agent.yaml.j2"
    dest: "{{ env_grafana_agent_files_path }}/grafana-agent.yaml"